.TH lcm-logplayer 1 2009-07-28 "LCM" "LCM"
.SH NAME
lcm-logplayer \- minimalist log playback tool
.SH SYNOPSIS
.TP 5
\fBlcm-logplayer \fI[options]\fR \fI[FILE]\fR

.SH DESCRIPTION
.PP
\fBlcm-logplayer\fR is a minimalist Lightweight Communications and Marshalling
logfile playback tool.  It provides a small set of options for controlling
logfile playback, and is primarily intended for situations where a command line
program is either desired or the only option.
In situations where both Java and a
graphical interface are available, \fBlcm-logplayer-gui\fR provides a more
featureful logplayer with a graphical user interface.

.SH OPTIONS
The following options are provided by \fBlcm-logplayer\fR
.TP
.B \-v, \-\-verbose
Print information about each packet.
.TP
.B \-s, \-\-speed=\fINUM\fR
Playback speed multipler.  Default is 1.0
.TP
.B \-e, \-\-regexp=\fIEXPR\fR
POSIX regular expression of channels to play.
.TP
.B \-l, \-\-lcm\-url=\fIURL\fR
Play logged messages on the specified LCM URL.
.TP
.B \-h, \-\-help
Shows some help text and exits

.SH SEE ALSO
.BR lcm-logplayer-gui (1)
.BR regex (7)

.SH COPYRIGHT

lcm-logplayer is part of the Lightweight Communications and Marshalling (LCM) project.
Permission is granted to copy, distribute and/or modify it under the terms of
the GNU Lesser General Public License as published by the Free Software
Foundation; either version 2.1 of the License, or (at your option) any later
version.  See the file COPYING in the LCM distribution for more details
regarding distribution.

LCM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public
License along with LCM; if not, write to the Free Software Foundation, Inc., 51
Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

.SH AUTHOR

This manual page was written by Albert Huang.
