.TH lcm-gen 1 2007-12-13 "LCM" "Lightweight Communications and Marshalling (LCM)"
.SH NAME
lcm-gen \- code generation tool.
.SH SYNOPSIS
.TP 5
\fBlcm-gen \fI[options]\fR \fIFILE\fR...

.SH DESCRIPTION
.PP
\fBlcm-gen\fR is the Lightweight Communications and Marshalling code generation
utility.  It takes as input one or more \fB.lcm\fR files containing LCM message
type definitions, and generates language-specific bindings for marshalling and
unmarshalling messages of the specified types.

Currently, \fBlcm-gen\fR is capable of generating language bindings for C,
Python, and Java.  One or more of \fB\-j\fR, \fB\-c\fR, or \fB\-p\fR must be
specified.

.SH OPTIONS
The following options are provided by \fBlcm-gen\fR:
.TP
.B \-c, \-\-c
Emit C code.
.TP
.B \-\-c-cpath \fIDIR\fR
Destination directory for generated .c files. (default: current directory)
.TP
.B \-\-c-hpath \fIDIR\fR
Destination directory for generated .h files. (default: current directory)
.TP
.B \-\-cinclude \fIDIR\fR
Generated #include lines reference this directory
.TP
.B \-j, \-\-java
Emit Java code.
.TP
.B \-\-jpath \fIDIR\fR
Destination base directory for generated Java files. (default: current
directory)
.TP
.B \-p, \-\-python
Emit Python code.
.TP
.B \-\-ppath \fIDIR\fR
Destination base directory for generated Python files. (default: current
directory)
.TP
.B \-\-lazy
Generate output file only if .lcm is newer than output file (or if output file
does not already exist).
.TP
.B \-d, \-\-debug
Show parsed files
.TP
.B \-t, \-\-tokenize
Show tokenization
.TP
.B \-h
Prints this help text and exits.

.SH COPYRIGHT

lcm-gen is part of the Lightweight Communications and Marshalling (LCM) project.
Permission is granted to copy, distribute and/or modify it under the terms of
the GNU Lesser General Public License as published by the Free Software
Foundation; either version 2.1 of the License, or (at your option) any later
version.  See the file COPYING in the LCM distribution for more details
regarding distribution.

LCM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public
License along with LCM; if not, write to the Free Software Foundation, Inc., 51
Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

.SH AUTHOR

This manual page was written by Albert Huang.
