.TH lcm_sink 1 2007-12-13 "LCM" "Lightweight Communications and Marshalling (LCM)"
.SH NAME
lcm_sink
.SH SYNOPSIS
.TP 5
\fBlcm_sink

.SH DESCRIPTION
.PP
\fBlcm_sink\fR is a utility for testing the Lightweight Communications library
(LC).  \fBlcm_source\fR listens for messages on all LC channels and
dumps the contents of the received messages to stdout.  It will attempt to
print unprintable characters, which may mess with some terminals when receiving
binary data.

.SH COPYRIGHT

lcm-sink is part of the Lightweight Communications and Marshalling (LCM) project.
Permission is granted to copy, distribute and/or modify it under the terms of
the GNU Lesser General Public License as published by the Free Software
Foundation; either version 2.1 of the License, or (at your option) any later
version.  See the file COPYING in the LCM distribution for more details
regarding distribution.

LCM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public
License along with LCM; if not, write to the Free Software Foundation, Inc., 51
Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

.SH AUTHOR

This manual page was written by Albert Huang.
