.TH lcm-logplayer-gui 1 2009-07-28 "LCM" "LCM"
.SH NAME
lcm-logplayer-gui - full featured log playback and editng tool
.SH SYNOPSIS
.TP 5
\fBlcm-logplayer-gui \fI[options]\fR \fI[FILE]\fR

.SH DESCRIPTION
.PP
\fBlcm-logplayer-gui\fR is the Lightweight Communications and Marshalling
log playback tool.  It provides a graphical user interface for playing logfiles
recorded with lcm-logger.  Features include random access, different playback 
speeds, channel suppression and remapping, and more.

\fBlcm-logplayer-gui\fR is written in Java, and uses the LCM Java bindings.
Consequently, running it requires a working Java virtual machine.

.SH OPTIONS
The following options are provided by \fBlcm-logplayer-gui\fR
.TP
.B \-l, \-\-lcm\-url=\fIURL\fR
Use the specified LCM URL
.TP
.B \-h, \-\-help
Shows some help text and exits

.SH SEE ALSO
.BR lcm-logger (1)
.BR lcm-logplayer (1)

.SH COPYRIGHT

lcm-logplayer-gui is part of the Lightweight Communications and Marshalling (LCM) project.
Permission is granted to copy, distribute and/or modify it under the terms of
the GNU Lesser General Public License as published by the Free Software
Foundation; either version 2.1 of the License, or (at your option) any later
version.  See the file COPYING in the LCM distribution for more details
regarding distribution.

LCM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public
License along with LCM; if not, write to the Free Software Foundation, Inc., 51
Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

.SH AUTHOR

This manual page was written by Albert Huang.
