.TH lcm-logplayer-gui 1 2007-12-13 "LCM" "LCM"
.SH NAME
lcm-logplayer-gui - full featured log playback and editng tool
.SH SYNOPSIS
.TP 5
\fBlcm-logplayer-gui \fI[options]\fR \fI[FILE]\fR

.SH DESCRIPTION
.PP
\fBlcm-logplayer-gui\fR is the Lightweight Communications and Marshalling
log playback tool.  It provides a graphical user interface for playing logfiles
recorded with lcm-logger.  Features include random access, different playback 
speeds, channel suppression and remapping, and more.

\fBlcm-logplayer-gui\fR is written in Java, and uses the LCM Java bindings.
Consequently, running it requires a working Java virtual machine.

.SH OPTIONS
There are currently no command-line options.

.SH SEE ALSO
.BR lcm-logger (1)
.BR lcm-logplayer (1)

.SH AUTHORS

This manual page was written by Albert Huang <ashuang@alum.mit.edu>.
Permission is granted to copy, distribute 
and/or modify this document under the terms of the GNU 
Free Documentation License, Version 1.1 or any later 
version published by the Free Software Foundation; with no 
Invariant Sections, no Front-Cover Texts and no Back-Cover 
Texts. 
