set(LCM_VERSION_MAJOR 1)
set(LCM_VERSION_MINOR 3)
set(LCM_VERSION_PATCH 1)
set(LCM_ABI_VERSION 1)

set(LCM_VERSION ${LCM_VERSION_MAJOR}.${LCM_VERSION_MINOR}.${LCM_VERSION_PATCH})
set(${PROJECT_NAME}_VERSION ${LCM_VERSION})
