.TH lc_example 1 2007-12-13 "LC" "Lightweight Communications (LC)"
.SH NAME
lc_example
.SH SYNOPSIS
.TP 5
\fBlc_example

.SH DESCRIPTION
.PP
\fBlc_example\fR is an example program that demonstrates how to use the
Lightweight Communications library (LC) for interprocess communications.
By itself, it's pretty useless aside from checking that LC is functioning
properly on a system.

.SH AUTHORS

This manual page was written by Albert Huang <ashuang@alum.mit.edu>.
Permission is granted to copy, distribute 
and/or modify this document under the terms of the GNU 
Free Documentation License, Version 1.1 or any later 
version published by the Free Software Foundation; with no 
Invariant Sections, no Front-Cover Texts and no Back-Cover 
Texts. 

