.TH lc_sink 1 2007-12-13 "LCM" "Lightweight Communications and Marshalling (LCM)"
.SH NAME
lc_sink
.SH SYNOPSIS
.TP 5
\fBlc_sink

.SH DESCRIPTION
.PP
\fBlc_sink\fR is a utility for testing the Lightweight Communications library
(LC).  \fBlc_source\fR listens for messages on all LC channels and
dumps the contents of the received messages to stdout.  It will attempt to
print unprintable characters, which may mess with some terminals when receiving
binary data.

.SH AUTHORS

This manual page was written by Albert Huang <ashuang@alum.mit.edu>.
Permission is granted to copy, distribute 
and/or modify this document under the terms of the GNU 
Free Documentation License, Version 1.1 or any later 
version published by the Free Software Foundation; with no 
Invariant Sections, no Front-Cover Texts and no Back-Cover 
Texts. 

